name: flutter_gsuite
description: Flutter package to interact with Gsuite (GoogleAPIs) resources
version: 0.0.1+1

publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.3.1
  hive: ^2.0.2
  http: ^1.1.0
  shared_extensions:
    path: /Users/henry/Developer/Projects/Packages/Flutter/packages/shared_extensions

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator: ^2.0.1
  lint: ^2.1.2
  mockito: ^5.0.2
