name: flutter_gsuite
description: Flutter package to interact with Gsuite (GoogleAPIs) resources
version: 0.0.1+1
author: Enrique Velasco

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_extensions:
    path: /Users/potter/Developer/Projects/Packages/Flutter/packages/shared_extensions
  dartz: ^0.10.0-nullsafety.1
  freezed_annotation: ^0.14.1
  googleapis: ^5.0.1
  googleapis_auth: ^1.0.0
  hive: ^2.0.2
  quiver: ^3.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  freezed: ^0.14.1
  hive_generator: ^1.0.1
  lint: ^1.5.3
  mockito: ^5.0.2

flutter: null
