name: flutter_gsuite
description: Flutter package to interact with Gsuite (GoogleAPIs) resources
version: 0.0.1+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  dartz: ^0.10.0-nullsafety.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.0.0
  hive: ^2.0.2
  http: ^0.13.5
  quiver: ^3.0.0
  shared_extensions:
    path: /Users/potter/Developer/Projects/Packages/Flutter/packages/shared_extensions

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator: ^1.0.1
  lint: ^1.5.3
  mockito: ^5.0.2

flutter: null
